language: minimal

deploy:
  # deploy master to production
  - provider: script
    script:  ssh $SSH_ACCESS_PROD -p $SSH_PORT_PROD "cd $WEBROOT_PATH_PROD && git checkout master && git pull origin master && exit"
    on:
      branch: feature/init-ci-cd