language: minimal

addons:
  ssh_known_hosts:
  - $SERVER_IP_PROD:$SSH_PORT_PROD

before_deploy:
  - eval "$(ssh-agent -s)" # Start ssh-agent cache
  - chmod 600 .travis/id_rsa # Allow read access to the private key
  - ssh-add .travis/id_rsa # Add the private key to SSH

deploy:
  # deploy master to production
  - provider: script
    script:  ssh -o StrictHostKeyChecking=no $SSH_USER_PROD@$SERVER_IP_PROD -p $SSH_PORT_PROD "cd $WEBROOT_PATH_PROD && git checkout master && git pull origin master && exit"
    on:
      branch: feature/init-ci-cd